name: 'Terraform'

#on:
 # push:
 #   branches: [ "main" ]
 # pull_request:
on:
  workflow_dispatch:
  
permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.9.8"

      - name: Terraform Init
        run: terraform -chdir=aws/environments/dev init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Tests
        run: |
          cd aws

          directories=$(find . -type d -name "tests" -exec dirname {} \;)

          for dir in $directories; do
            echo "Running terraform test in $dir"
            (cd "$dir" && terraform init && terraform test)
          done

      - name: Terraform Plan
        run: terraform -chdir=aws/environments/dev plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=aws/environments/dev apply -auto-approve -input=false
